---
title: "Figures for Graduation Presentation"
author: "Brian Gulbis"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    code_folding: hide
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(stringr)
library(forcats)
library(lubridate)
library(broom)
library(qicharts)
library(themebg)

x <- dirr::get_rds("../data/tidy")

end_date <- "2017-05-07"
pilot_start <- "2017-01-30"
pilot_end <- "2017-03-05"
pilot2_start <- "2017-04-16"
baseline <- "2016-12-31"

hvi <- c("HH CVICU", "HH CVIMU", "HH HFIC", "HH HFIM", "HH 5HVI", "HH CCU", "HVI CIMU")
# hvi <- "HH CVICU"

orders_levels <- full_join(vanc_levels, orders_valid, by = c("pie.id", "order.id")) %>%
    filter(event.unit %in% hvi | (is.na(event.unit) & order.unit %in% hvi)) %>%
    mutate(not_collected = is.na(Collected) & is.na(lab.result) & (!mult_levels | is.na(mult_levels)),
           location = coalesce(event.unit, order.unit),
           month = floor_date(detail.datetime, unit = "month"),
           week = floor_date(detail.datetime, unit = "week"),
           day = wday(detail.datetime, label = TRUE, abbr = TRUE),
           hour = hour(detail.datetime),
           day_order = wday(order.datetime, label = TRUE, abbr = TRUE),
           hour_order = hour(order.datetime),
           exceed_2hr = abs(collect_detail_diff) > 120,
           group = if_else(detail.datetime >= ymd(pilot_start, tz = "US/Central") & detail.datetime < ymd(pilot2_start, tz = "US/Central"), "pilot1", 
                           if_else(detail.datetime >= ymd(pilot2_start, tz = "US/Central"), "pilot2", "baseline")), 
           future_order = order_detail_diff > 1,
           dispatch_late = Dispatched > detail.datetime + minutes(5)) %>%
    dmap_at(c("timely120", "timely60", "appropriate"), ~ coalesce(.x, FALSE)) %>%
    dmap_at("future_order", ~if_else(.x, "Future", "Now"))

data_orders <- orders_levels %>%
    filter(priority %in% c("Routine", "Stat", "Timed Study"),
           detail.datetime >= order.datetime - hours(1)) %>%
    mutate(priority = if_else(early_am, "Early AM", priority))

collected <- data_orders %>%
    filter(!is.na(Collected),
           order.datetime <= ymd(end_date)) %>%
    group_by(event.unit, group) %>%
    summarize(collected = n(),
              timely = sum(appropriate, na.rm = TRUE),
              early = sum(early, na.rm = TRUE),
              late = sum(late, na.rm = TRUE),
              late_2hr = sum(exceed_2hr, na.rm = TRUE)) 

not_done <- data_orders %>%
    filter(is.na(Collected),
           is.na(lab.result),
           order.datetime <= ymd(end_date)) %>%
    group_by(order.unit, group) %>%
    count %>%
    rename(not_done = n)

requests <- orders_requests %>%
    mutate(group = if_else(order.datetime >= ymd(pilot_start, tz = "US/Central") & order.datetime < ymd(pilot2_start, tz = "US/Central"), "pilot1", 
                           if_else(order.datetime >= ymd(pilot2_start, tz = "US/Central"), "pilot2", "baseline"))) %>%
    filter(order.datetime <= ymd(end_date)) %>%
    group_by(order.unit, group) %>%
    count %>%
    rename(requests = n) %>%
    filter(order.unit %in% hvi)

early_am <- orders_early_am %>%
    mutate(group = if_else(order.datetime >= ymd(pilot_start, tz = "US/Central") & order.datetime < ymd(pilot2_start, tz = "US/Central"), "pilot1", 
                           if_else(order.datetime >= ymd(pilot2_start, tz = "US/Central"), "pilot2", "baseline"))) %>%
    filter(order.datetime <= ymd(end_date)) %>%
    group_by(order.unit, group) %>%
    count() %>%
    rename(early_am = n) %>%
    filter(order.unit %in% hvi) 

priority <- data_orders %>%
    filter(!is.na(Collected),
           order.datetime <= ymd(end_date),
           priority %in% c("Routine", "Stat", "Timed Study")) %>%
    count(event.unit, group, priority) %>%
    group_by(event.unit, group) %>%
    spread(priority, n)

# percent_timely = timely / collected,
           
totals_units <- left_join(collected, not_done, by = c("event.unit" = "order.unit", "group")) %>%
    left_join(requests, by = c("event.unit" = "order.unit", "group")) %>%
    left_join(early_am, by = c("event.unit" = "order.unit", "group")) %>%
    mutate(total = collected + not_done,
           defects = total - timely,
           percent_not_done = not_done / total * 100,
           percent_appropriate = timely / total * 100,
           percent_untimely = (1 - timely / total) * 100,
           percent_exceed_2hr = late_2hr / total * 100,
           percent_requests = requests / total * 100,
           percent_early_am = early_am / total * 100)

totals_hvi <- totals_units %>%
    group_by(group) %>%
    summarize_at(vars(collected, timely, early, late, late_2hr, not_done, requests, early_am, total, defects), funs(sum), na.rm = TRUE) %>%
    mutate(event.unit = "HVI",
           percent_not_done = not_done / total * 100,
           percent_appropriate = timely / total * 100,
           percent_untimely = (1 - timely / total) * 100,
           percent_exceed_2hr = late_2hr / total * 100,
           percent_requests = requests / total * 100,
           percent_early_am = early_am / total * 100) 

totals <- bind_rows(totals_units, totals_hvi) %>%
    select(event.unit, group, num_levels = total, everything()) %>%
    filter(!is.na(event.unit))

cvicu_reqs <- orders_requests %>%
    mutate(group = if_else(order.datetime >= ymd(pilot_start, tz = "US/Central") & order.datetime < ymd(pilot2_start, tz = "US/Central"), "pilot1", 
                           if_else(order.datetime >= ymd(pilot2_start, tz = "US/Central"), "pilot2", "baseline"))) %>%
    filter(order.unit == "HH CVICU",
           order.datetime <= ymd(end_date)) %>%
    mutate(priority = "Request") %>%
    select(pie.id, group, priority, action.provider.role)

cvicu_orders <- data_orders %>%
    filter(event.unit == "HH CVICU",
           detail.datetime >= order.datetime - hours(1)) %>%
    full_join(cvicu_reqs, by = c("pie.id", "group", "priority", "action.provider.role"))

cvicu <- orders_levels %>%
    filter(location == "HH CVICU",
           month != "2016-03-01") 

weekly_requests <- orders_requests %>%
    filter(order.unit == "HH CVICU",
           is.na(cancel.datetime),
           !is.na(action.provider.role)) %>%
    mutate(week = floor_date(request.datetime, unit = "week")) %>%
    group_by(week) %>%
    count() %>%
    rename(requests = n) %>%
    filter(week != "2016-03-27", week != end_date)

weekly_levels <- cvicu %>%
    filter(week != "2016-03-27", 
           week != end_date,
           !is.na(Dispatched)) %>%
    group_by(week) %>%
    summarize(levels = n(),
             early_am = sum(early_am),
             appropriate = sum(appropriate),
             uncollected = sum(not_collected)) %>%
    full_join(weekly_requests, by = "week") %>%
    dmap_at(c("requests", "uncollected"), ~ coalesce(.x, 0L))

cvicu_dispatch <- data_orders %>%
    filter(event.unit == "HH CVICU",
           !is.na(Dispatched)) %>%
    mutate(dispatch_min = round_date(Dispatched, unit = "15 mins"),
           dispatch_min = minute(dispatch_min),
           dispatch_hour = round_date(Dispatched, unit = "hour"),
           dispatch_hour = hour(dispatch_hour))
```

```{r, fig.cap="Timeliness of orders for vancomycin levels in CVICU placed during the baseline period of April to December 2016"}
totals %>%
    filter(event.unit == "HH CVICU") %>%
    select(event.unit, group, Untimely = percent_untimely, Uncollected = percent_not_done) %>%
    gather(nm, val, Untimely, Uncollected) %>%
    # dmap_at("val", ~ round(.x * 100, 0)) %>%
    # arrange(desc(val)) %>%
    # dmap_at("nm", factor) %>%
    # mutate(grp = if_else(str_detect(nm, "Untimely|Uncollected"), "Timeliness", "Order Type")) %>%
    ggplot(aes(x = nm, y = val, fill = group)) +
    geom_bar(stat = "identity", position = "dodge") +
    # facet_wrap(~ grp, scales = "free_x") +
    # scale_x_discrete("", labels = c("Untimely", "Early AM", "Requests", "Uncollected")) +
    xlab("") +
    ylab("Vancomycin Level Orders (%)") +
    scale_fill_brewer(palette = "Set1") +
    coord_cartesian(ylim = c(0, 100)) +
    theme_bg(xticks = FALSE)
```

```{r, fig.cap="Types of orders for vancomycin levels in CVICU placed during the baseline period of April to December 2016"}
cvicu_orders %>%
    dmap_at("priority", fct_infreq) %>%
    ggplot(aes(x = priority, fill = group)) +
    geom_bar(position = "dodge") +
    xlab("Order Type") +
    ylab("Number of Orders") +
    scale_fill_brewer(palette = "Set1") +
    theme_bg(xticks = FALSE)
```

```{r, fig.cap="Providers placing orders for vancomycin levels in CVICU during the baseline period of April to December 2016"}
cvicu_orders %>%
    filter(!is.na(action.provider.role)) %>%
    dmap_at("action.provider.role", fct_infreq) %>%
    dmap_at("action.provider.role", fct_lump, n = 4) %>%
    dmap_at("action.provider.role", fct_rev) %>%
    ggplot(aes(x = action.provider.role, fill = group)) +
    geom_bar(position = "dodge") +
    xlab("Provider Type") +
    ylab("Number of Orders") +
    scale_fill_brewer(palette = "Set1") +
    theme_bg(yticks = FALSE) +
    coord_flip()
```

```{r, fig.cap="Percent change in outcomes following pilot intervention relative to baseline period"}
weekly_levels %>%
    mutate_at(c("early_am", "appropriate", "uncollected", "requests"), funs(. / levels)) %>%
    mutate(pilot = ymd(week, tz = "US/Central") >= ymd(pilot_start, tz = "US/Central") & ymd(week, tz = "US/Central") <= ymd(pilot2_start, tz = "US/Central")) %>%
    group_by(pilot) %>%
    summarize_if(is.numeric, mean) %>%
    gather(key, value, early_am:requests) %>%
    select(-levels) %>%
    spread(pilot, value) %>%
    rename(baseline = `FALSE`, pilot = `TRUE`) %>%
    mutate(change = round((pilot / baseline * 100) - 100, 0)) %>%
    dmap_at("key", factor, levels = c("early_am", "requests", "appropriate", "uncollected")) %>%
    ggplot(aes(x = key, y = change)) +
    geom_bar(stat = "identity", width = 0.75) + 
    geom_hline(yintercept = 0, color = "light gray") +
    scale_x_discrete("", labels = c("Early AM", "Requests", "Timely", "Uncollected")) +
    scale_y_continuous("Change (%)", limits = c(-100, 100), breaks = seq(-100, 100, 25)) +
    theme_bg(xticks = FALSE) 
```

```{r, fig.cap="Percent change in outcomes following second pilot intervention relative to baseline period"}
weekly_levels %>%
    mutate_at(c("early_am", "appropriate", "uncollected", "requests"), funs(. / levels)) %>%
    mutate(pilot = ymd(week, tz = "US/Central") >= ymd(pilot2_start, tz = "US/Central") & ymd(week, tz = "US/Central") <= ymd(end_date, tz = "US/Central")) %>%
    group_by(pilot) %>%
    summarize_if(is.numeric, mean) %>%
    gather(key, value, early_am:requests) %>%
    select(-levels) %>%
    spread(pilot, value) %>%
    rename(baseline = `FALSE`, pilot = `TRUE`) %>%
    mutate(change = round((pilot / baseline * 100) - 100, 0)) %>%
    dmap_at("key", factor, levels = c("early_am", "requests", "appropriate", "uncollected")) %>%
    ggplot(aes(x = key, y = change)) +
    geom_bar(stat = "identity", width = 0.75) + 
    geom_hline(yintercept = 0, color = "light gray") +
    scale_x_discrete("", labels = c("Early AM", "Requests", "Timely", "Uncollected")) +
    scale_y_continuous("Change (%)", limits = c(-100, 100), breaks = seq(-100, 100, 25)) +
    theme_bg(xticks = FALSE) 
```

```{r, fig.cap="Percent change in outcomes following second pilot intervention relative to first pilot period"}
weekly_levels %>%
    filter(ymd(week, tz = "US/Central") >= ymd(pilot_start, tz = "US/Central")) %>%
    mutate_at(c("early_am", "appropriate", "uncollected", "requests"), funs(. / levels)) %>%
    mutate(pilot = ymd(week, tz = "US/Central") >= ymd(pilot2_start, tz = "US/Central") & ymd(week, tz = "US/Central") <= ymd(end_date, tz = "US/Central")) %>%
    group_by(pilot) %>%
    summarize_if(is.numeric, mean) %>%
    gather(key, value, early_am:requests) %>%
    select(-levels) %>%
    spread(pilot, value) %>%
    rename(baseline = `FALSE`, pilot = `TRUE`) %>%
    mutate(change = round((pilot / baseline * 100) - 100, 0)) %>%
    dmap_at("key", factor, levels = c("early_am", "requests", "appropriate", "uncollected")) %>%
    ggplot(aes(x = key, y = change)) +
    geom_bar(stat = "identity", width = 0.75) + 
    geom_hline(yintercept = 0, color = "light gray") +
    scale_x_discrete("", labels = c("Early AM", "Requests", "Timely", "Uncollected")) +
    scale_y_continuous("Change (%)", limits = c(-100, 100), breaks = seq(-100, 100, 25)) +
    theme_bg(xticks = FALSE) 
```

```{r, fig.cap="Percent change in weekly outcomes relative to the weekly mean during the baseline period", fig.height=4}
baseline <- weekly_levels %>%
    mutate_at(c("early_am", "appropriate", "uncollected", "requests"), funs(. / levels * 100)) %>%
    filter(week < mdy("1/29/2017", tz = "US/Central")) %>%
    summarize_if(is.numeric, mean) %>%
    select(-levels) %>%
    gather(key, value) %>%
    rename(baseline = value)

weekly_levels %>%
    mutate_at(c("early_am", "appropriate", "uncollected", "requests"), funs(. / levels * 100)) %>%
    filter(week >= mdy("1/29/2017", tz = "US/Central")) %>%
    gather(key, value, early_am:requests) %>%
    left_join(baseline, by = "key") %>%
    mutate(change = (value / baseline * 100) - 100) %>%
    dmap_at("key", factor, levels = c("early_am", "requests", "appropriate", "uncollected")) %>%
    ggplot(aes(x = week, y = change)) +
    geom_bar(stat = "identity") +
    geom_hline(yintercept = 0, color = "light gray") +
    facet_wrap(~ key, labeller = labeller(key = c(early_am = "Early AM", requests = "Requests", appropriate = "Timely", uncollected = "Uncollected"))) +
    xlab("Week Beginning") +
    ylab("Change (%)") +
    theme_bg(xticks = FALSE) 
```

```{r, warning=FALSE, fig.cap="Distribution of time from task dispatch to scheduled collection"}
ggplot(cvicu_dispatch, aes(x = event.unit, y = dispatch_detail_diff)) +
    geom_hline(yintercept = 0, color = "light grey") +
    geom_boxplot() +
    # facet_wrap(~ future_order) +
    xlab("Collection Priority") +
    scale_y_continuous("Dispatch to Scheduled Collection (Hours)", breaks = seq(0, 30, 6)) +
    theme_bg(xticks = FALSE)
```

```{r, warning=FALSE, fig.cap="Distribution of time from task dispatch to scheduled collection for Future vs. Now orders"}
ggplot(cvicu_dispatch, aes(x = priority, y = dispatch_detail_diff)) +
    geom_hline(yintercept = 0, color = "light grey") +
    geom_boxplot() +
    # facet_wrap(~ future_order) +
    xlab("Collection Priority") +
    scale_y_continuous("Dispatch to Scheduled Collection (Hours)", breaks = seq(0, 30, 6)) +
    theme_bg(xticks = FALSE)
```

```{r}
ggplot(cvicu_dispatch, aes(x = dispatch_detail_diff * 60, fill = dispatch_late)) +
    geom_vline(xintercept = 0, color = "grey") +
    geom_hline(yintercept = 0, color = "light grey") +
    geom_histogram(binwidth = 15, color = "white") +
    # facet_wrap(~ priority, scales = "free_y") +
    scale_x_continuous("Time from Task Dispatch to Scheduled Collection (minutes)", breaks = seq(-12 * 60, 12 * 60, 60)) +
    ylab("Number Dispatched") +
    scale_fill_brewer("", palette = "Set1", direction = -1, labels = c("Before Level Due", "After Level Due")) +
    coord_cartesian(xlim = c(-2 * 60, 4 * 60)) +
    theme_bg(base_family = "serif") +
    theme(legend.position = "bottom")
```

```{r}
ggplot(cvicu_dispatch, aes(x = dispatch_detail_diff * 60, fill = dispatch_late)) +
    geom_vline(xintercept = 0, color = "grey") +
    geom_hline(yintercept = 0, color = "light grey") +
    geom_histogram(binwidth = 15, color = "white") +
    facet_wrap(~ priority, scales = "free_y") +
    scale_x_continuous("Time from Task Dispatch to Scheduled Collection (minutes)", breaks = seq(-12 * 60, 12 * 60, 2 * 60)) +
    ylab("Number Dispatched") +
    scale_fill_brewer("", palette = "Set1", direction = -1, labels = c("Before Level Due", "After Level Due")) +
    coord_cartesian(xlim = c(-2 * 60, 4 * 60)) +
    theme_bg(base_family = "serif") +
    theme(legend.position = "bottom")
```


```{r, fig.cap="Hour of day when Routine and Timed Study orders dispatch"}
cvicu_dispatch %>%
    filter(priority %in% c("Routine", "Timed Study")) %>%
    count(priority, dispatch_hour) %>%
    ggplot(aes(x = dispatch_hour, y = n)) +
    geom_bar(stat = "identity") +
    scale_x_continuous("Dispatch Hour of Day", breaks = seq(0, 24, 6)) +
    ylab("Number of Orders") +
    scale_fill_brewer("Order Priority") +
    theme_bg()
```

# Exploration

```{r, warning=FALSE, fig.cap="Number of uncollected levels by collection priority and Now vs. Future orders"}
data_orders %>%
    filter(location == "HH CVICU",
           not_collected,
           !is.na(Dispatched)) %>%
    dmap_at("priority", fct_infreq) %>%
    count(priority, pilot) %>%
    group_by(pilot) %>%
    mutate_at("n", funs(. / sum(n) * 100)) %>%
    ggplot(aes(x = priority, y = n)) +
    geom_bar(stat = "identity") +
    facet_wrap(~ pilot, labeller = labeller(pilot = c(`FALSE` = "Baseline", `TRUE` = "Pilot"))) +
    xlab("Collection Priority") +
    ylab("Uncollected Levels (%)") +
    theme_bg(xticks = FALSE)
```

```{r}
x <- data_orders %>%
    filter(location == "HH CVICU",
           not_collected,
           pilot,
           !is.na(Dispatched)) %>%
    select(pie.id, detail.datetime, Dispatched, Discontinued, priority, mult_levels, everything())
```

# Uncollected

```{r, fig.cap="Types of orders for vancomycin levels which were uncollected in CVICU during pilot"}
orders_levels %>%
    filter(not_collected,
           location == "HH CVICU",
           pilot) %>%
    dmap_at("priority", fct_infreq) %>%
    ggplot(aes(x = priority)) +
    geom_bar(aes(fill = future_order)) +
    xlab("Order Type") +
    ylab("Number of Orders") +
    theme_bg(xticks = FALSE)
```

```{r, fig.cap="Comparison of distribution of time from dispatch to scheduled collection among levels which were collected an which were not in CVICU during pilot period"}
orders_levels %>%
    filter(location == "HH CVICU",
           pilot) %>%
    ggplot(aes(x = factor(not_collected), y = dispatch_detail_diff)) +
    geom_boxplot() +
    theme_bg(xticks = FALSE)
```

```{r, fig.cap="Comparison of distribution of time from dispatch to scheduled collection among levels which were collected an which were not in CVICU during pilot period"}
orders_levels %>%
    filter(location == "HH CVICU",
           pilot) %>%
    ggplot(aes(x = dispatch_detail_diff)) +
    geom_histogram() +
    facet_wrap(~ not_collected) +
    theme_bg(xticks = FALSE)
```

# Nurse Variation

```{r, fig.cap="Comparison of time difference between scheduled and actual collection by nurse for Timed Study orders which were due on the same shift", fig.height=10}
rn <- cvicu_orders %>%
    mutate(hour_collect = hour(Collected),
           same_shift = (shift == "day" & (hour_collect >= 7 & hour_collect < 19)) |
               (shift == "night" & (hour_collect >= 19 | hour_collect < 7))) %>%
    filter(!is.na(rn_collect),
           str_detect(rn_collect, "RN"),
           priority == "Timed Study",
           future_order == "Future",
           same_shift) %>%
    dmap_at("rn_collect", as_factor) %>%
    mutate(rn_collect = fct_reorder(rn_collect, x = collect_detail_diff, fun = median, .desc = TRUE))
    # dmap_at("rn_collect", fct_lump, n = 50) 


ggplot(rn, aes(x = rn_collect, y = collect_detail_diff)) +
    geom_rect(aes(xmin = levels(rn$rn_collect)[nlevels(rn$rn_collect)], 
                  xmax = levels(rn$rn_collect)[1],
                  ymin = -60,
                  ymax = 60),
              fill = "light gray") +
    geom_hline(yintercept = 0, color = "dark grey") +
    geom_boxplot() +
    scale_y_continuous("Time from Scheduled to Actual Collection (minutes)", breaks = seq(-360, 360, 60)) +
    xlab("") +
    labs(caption = "The shaded area represents the target for timely collection") +
    coord_flip(ylim = c(-360, 360)) +
    theme_bg()
```

```{r, fig.cap="Number of levels drawn by each nurse for Timed Study orders", fig.height=10}
rn %>%
    dmap_at("rn_collect", fct_infreq) %>%
    dmap_at("rn_collect", fct_rev) %>%
    ggplot(aes(x = rn_collect, fill = appropriate)) +
    geom_bar() +
    xlab("") +
    scale_y_continuous("Number of Levels", breaks = seq(0, 20, 2)) +
    scale_fill_brewer("", palette = "Set1", labels = c("Untimely", "Timely")) +
    coord_flip() +
    theme_bg()

```

